name: Build Native Windows Executable

on:
  push:
    branches: [ "main" ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup GraalVM
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '11'                      # или '17', смотрите совместимость проекта
          distribution: 'graalvm'                  # можно также 'liberica'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          native-image-job-reports: 'true'
          cache: 'gradle'

      - name: Check versions
        run: |
          java --version
          native-image --version

      - name: Build with Gradle
        # Используем задачу nativeCompile, если она добавлена в build.gradle
        run: ./gradlew nativeCompile --no-daemon
        shell: bash

      - name: Upload native executable
        uses: actions/upload-artifact@v4
        with:
          name: AtsumeruManager-Windows-x64
          path: build/native/nativeCompile/*.exe
